export const GET_DOGS = 'GET_DOG'
export const GET_BY_NAME = 'GET_BY_NAME'
export const ORDER = 'ORDER'
export const GET_DETAIL = 'GET_DETAIL'
export const FILTER_TEMP = 'FILTER_TEMP'
export const ALL_TEMPS = 'ALL_TEMPS'
export const FILTER_ORIGIN = 'FILTER_ORIGIN'